export const AGENTS = [
  {
    id: 'RouterAgent',
    label: 'Auto-Route',
    description: 'Automatically picks the best agent for your prompt.',
    icon: '⚡',
    model: 'Auto',
    isRouter: true,
  },
  {
    id: 'MailAgent',
    label: 'Mail',
    description: 'Email + calendar assistant. Can read, draft, reply, schedule — mutations always ask you to approve.',
    example: 'Reply to the latest email from Sarah confirming Thursday at 10am.',
    icon: '✉',
    model: 'General LLM',
  },
  {
    id: 'AlertAgent',
    label: 'Alert',
    description: 'Summarises alerts and suggests first-response actions.',
    example: 'Summarise these Zabbix alerts and flag anything critical.',
    icon: '🚨',
    model: 'General LLM',
  },
  {
    id: 'AnalystAgent',
    label: 'Analyst',
    description: 'Analyses structured data, logs, and metrics to extract insight.',
    example: 'Analyse this CSV of login attempts and highlight anomalies.',
    icon: '📊',
    model: 'General LLM',
  },
  {
    id: 'ArchitectAgent',
    label: 'Architect',
    description: 'Designs system architectures and evaluates trade-offs.',
    example: 'Design a highly-available file share for 200 Windows clients.',
    icon: '🏛',
    model: 'Qwen3-Coder 80B',
  },
  {
    id: 'AssistantAgent',
    label: 'Assistant',
    description: 'General-purpose conversational assistant for everyday questions.',
    example: 'Explain the difference between SCCM and Intune in plain English.',
    icon: '💬',
    model: 'General LLM',
  },
  {
    id: 'ClientBriefAgent',
    label: 'Client Brief',
    description: 'Turns raw notes into polished client-facing briefs.',
    example: 'Write a one-page brief for a 50-seat Intune migration.',
    icon: '📋',
    model: 'General LLM',
  },
  {
    id: 'CoderAgent',
    label: 'Coder',
    description: 'Writes, debugs, and refactors production code in any language.',
    example: 'Write a Python script to parse Intune CSV exports.',
    icon: '💻',
    model: 'Qwen3-Coder 80B',
  },
  {
    id: 'DemoAgent',
    label: 'Demo',
    description: 'Builds runnable demo scenarios and walk-through scripts.',
    example: 'Create a demo showing Autopilot enrolment end to end.',
    icon: '🎬',
    model: 'Qwen3-Coder 80B',
  },
  {
    id: 'DeployAgent',
    label: 'Deploy',
    description: 'Produces deployment plans, runbooks, and rollout checklists.',
    example: 'Draft a deployment plan for Defender for Endpoint.',
    icon: '🚀',
    model: 'Qwen3-Coder 80B',
  },
  {
    id: 'DiagramAgent',
    label: 'Diagram',
    description: 'Generates Mermaid diagrams for architecture and flows.',
    example: 'Diagram the Alice request flow from browser to model.',
    icon: '📐',
    model: 'General LLM',
  },
  {
    id: 'DocAgent',
    label: 'Docs',
    description: 'Writes clear technical documentation and how-to guides.',
    example: 'Document how to rotate the Alice admin password.',
    icon: '📝',
    model: 'General LLM',
  },
  {
    id: 'GitAgent',
    label: 'Git',
    description: 'Helps with Git workflows, commits, merges, and history.',
    example: 'Write a commit message for these staged changes.',
    icon: '🌿',
    model: 'General LLM',
  },
  {
    id: 'HealthAgent',
    label: 'Health',
    description: 'Reports on service health and interprets diagnostics.',
    example: 'Interpret this systemctl status output for alice-web.',
    icon: '🩺',
    model: 'General LLM',
  },
  {
    id: 'ImageAgent',
    label: 'Image',
    description: 'Generates images via a local ComfyUI pipeline.',
    example: 'Generate a dark, minimal hero image for a proposal deck.',
    icon: '🖼',
    model: 'ComfyUI',
  },
  {
    id: 'InfraAgent',
    label: 'Infra',
    description: 'Plans and scripts infrastructure changes for Windows and Linux.',
    example: 'Script the provisioning of a new Hyper-V VM from a template.',
    icon: '🏗',
    model: 'Qwen3-Coder 80B',
  },
  {
    id: 'LogWatchAgent',
    label: 'Log Watch',
    description: 'Watches log streams for errors and surfaces likely causes.',
    example: 'Scan these nginx error logs for the last hour and summarise.',
    icon: '🔍',
    model: 'General LLM',
  },
  {
    id: 'ProposalAgent',
    label: 'Proposal',
    description: 'Drafts client-ready proposals with scope, cost, and risk.',
    example: 'Draft a proposal for a 100-seat Windows 11 refresh.',
    icon: '📄',
    model: 'Qwen3-Coder 80B',
  },
  {
    id: 'ResearchAgent',
    label: 'Research',
    description: 'Deep-dives into technical topics and cites sources.',
    example: 'Research best practices for Entra ID Conditional Access.',
    icon: '🔬',
    model: 'Qwen3-Coder 80B',
  },
  {
    id: 'ReviewAgent',
    label: 'Review',
    description: 'Reviews code for bugs, style, and security issues.',
    example: 'Review this PowerShell script for unsafe parameter handling.',
    icon: '🔎',
    model: 'Qwen3-Coder 80B',
  },
  {
    id: 'SlideAgent',
    label: 'Slides',
    description: 'Generates downloadable PowerPoint presentations.',
    example: 'Build a five-slide intro deck for a Alice client demo.',
    icon: '📊',
    model: 'General LLM',
  },
  {
    id: 'TestAgent',
    label: 'Test',
    description: 'Writes unit and integration tests for existing code.',
    example: 'Write pytest tests for this Alice auth helper.',
    icon: '🧪',
    model: 'Qwen3-Coder 80B',
  },
  {
    id: 'VideoAgent',
    label: 'Video',
    description: 'Generates short AI videos from text descriptions using LTX-2.',
    example: 'A time-lapse of a modern office building from dawn to dusk, clouds moving across the sky.',
    icon: '🎬',
    model: 'ComfyUI',
  },
  {
    id: 'VideoScriptAgent',
    label: 'Video Script',
    description: 'Writes scripts and shot lists for short technical videos.',
    example: 'Write a 90-second video script explaining Alice.',
    icon: '🎥',
    model: 'General LLM',
  },
];

export const MODEL_BADGE_CLASS = {
  'Qwen3-Coder 80B': 'badge-coder',
  'General LLM': 'badge-general',
  'ComfyUI': 'badge-image',
  'Auto': 'badge-auto',
};
